server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  mvc:
    throwExceptionIfNoHandlerFound: true

datasource:
  master:
    url: jdbc:mysql://localhost:3306/master_db
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    liquibase:
      change-log: "classpath:liquibase/master_db/changelog.yaml"
      enabled: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 100000
      max-lifetime: 3000000
      pool-name: MasterHikariPool

  slave:
    url: jdbc:mysql://localhost:3309/master_db
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    liquibase:
      change-log: "classpath:liquibase/slave_db/changelog.yaml"
      enabled: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 100000
      max-lifetime: 3000000
      pool-name: SlaveHikariPool
