server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  mvc:
    throwExceptionIfNoHandlerFound: true

datasource:
  master:
    url: jdbc:postgresql://localhost:5432/master_db
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    liquibase:
      change-log: "classpath:liquibase/master_db/changelog.yaml"
      enabled: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 100000
      max-lifetime: 3000000
      pool-name: MasterHikariPool

  slave:
    url: jdbc:postgresql://localhost:5433/master_db
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 100000
      max-lifetime: 3000000
      pool-name: SlaveHikariPool
